import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
import {managerReply} from "./chat/managerChat";

type Status="IDLE"|"WALKING"|"WORKING"|"THINKING"|"MEETING"|"SUCCESS"|"ERROR";
type Agent={id:string;name:string;role:string;color:string;accent:string;desk:[number,number,number];waypoints:[number,number,number][];task:string;status:Status;icon:string};
const agents:Agent[]=[
{id:"bug-solver",name:"Bug Solver",role:"Repair & Fix",color:"#69435d",accent:"#ff9fbd",desk:[7,0,1.2],waypoints:[[7,0,1.2],[5,0,3],[2,0,4],[7,0,1.2]],task:"Repairing verified defects before retry",status:"WORKING",icon:"F"},

{id:"manager",name:"Manager",role:"Team Lead",color:"#355c7d",accent:"#7dd3fc",desk:[-7,0,-4],waypoints:[[-7,0,-4],[-2,0,-1],[0,0,2],[-7,0,-4]],task:"Coordinating the active site queue",status:"WORKING",icon:"M"},
{id:"researcher",name:"Researcher",role:"Research & Discovery",color:"#426b57",accent:"#8be3ad",desk:[-3.5,0,-4],waypoints:[[-3.5,0,-4],[-5,0,1],[-1,0,3],[-3.5,0,-4]],task:"Checking authorized sources",status:"THINKING",icon:"R"},
{id:"image-agent",name:"Image Agent",role:"Authorized Media",color:"#6b4c7c",accent:"#d8a7ff",desk:[0,0,-4],waypoints:[[0,0,-4],[4,0,-1],[5,0,2],[0,0,-4]],task:"Preparing approved media assets",status:"WORKING",icon:"I"},
{id:"bug-hunter",name:"Bug Hunter",role:"Find & Diagnose",color:"#7a5838",accent:"#ffcb7a",desk:[3.5,0,-4],waypoints:[[3.5,0,-4],[5,0,2],[2,0,4],[3.5,0,-4]],task:"Scanning the current build",status:"WALKING",icon:"B"},
{id:"seo-agent",name:"SEO Agent",role:"Search Specialist",color:"#2d6570",accent:"#75e1ed",desk:[7,0,-4],waypoints:[[7,0,-4],[4,0,3],[0,0,3],[7,0,-4]],task:"Optimizing discoverability signals",status:"WORKING",icon:"S"},
{id:"idea-builder",name:"Idea Builder",role:"New Site Ideas",color:"#806b32",accent:"#ffe18a",desk:[-4.8,0,4],waypoints:[[-4.8,0,4],[-1,0,5],[1,0,2],[-4.8,0,4]],task:"Developing the next site concept",status:"THINKING",icon:"N"},
{id:"publisher",name:"Publisher",role:"Build & Deploy",color:"#315d77",accent:"#8fd4ff",desk:[0,0,4],waypoints:[[0,0,4],[5,0,4],[6,0,1],[0,0,4]],task:"Preparing a verified deployment",status:"WORKING",icon:"P"},
{id:"qa",name:"QA Agent",role:"Final Verification",color:"#35665c",accent:"#8df0c2",desk:[4.8,0,4],waypoints:[[4.8,0,4],[2,0,1],[-2,0,1],[4.8,0,4]],task:"Running final verification checks",status:"SUCCESS",icon:"Q"}
];

const statusTone=(s:Status)=>({IDLE:"#718096",WALKING:"#60a5fa",WORKING:"#4ade80",THINKING:"#c084fc",MEETING:"#fbbf24",SUCCESS:"#34d399",ERROR:"#fb7185"}[s]);

type SiteRecord={id:string;name:string;repository:string;branch:string;live_url:string;enabled:boolean;authorized:boolean;description?:string;media?:{enabled:boolean;authorized_source:boolean;path:string}};

function SitePanel({sites,selectedSite,setSelectedSite,onClose}:{sites:SiteRecord[];selectedSite:string;setSelectedSite:(id:string)=>void;onClose:()=>void}){
 const [openAdd,setOpenAdd]=useState(false); const [form,setForm]=useState({id:"",name:"",repository:"",branch:"main",live_url:"",description:"",media_path:"chapter-images/"});
 const request=(title:string,command:any)=>{const body="<!-- site-manager-command\\n"+JSON.stringify(command,null,2)+"\\n-->"; const url="https://github.com/WebControlerAgent/WebControlerAgent.github.io/issues/new?title="+encodeURIComponent(title)+"&body="+encodeURIComponent(body); window.open(url,"_blank","noopener,noreferrer");}; const submit=(e:React.FormEvent)=>{e.preventDefault(); if(!form.id||!form.name||!form.repository||!form.live_url)return; request("[Site Manager] Add "+form.name,{action:"add",...form,authorized:true,enabled:true,media_enabled:!!form.media_path}); setOpenAdd(false); };
 return <div className="site-overlay"><div className="site-panel"><div className="site-panel-head"><div><b>SITES CONTROL</b><small>Authorized GitHub targets • one active site at a time</small></div><button onClick={onClose}>×</button></div><div className="site-list">{sites.map(s=><div key={s.id} className={"site-card-wrap "+(selectedSite===s.id?"active":"")}><button className="site-card" onClick={()=>setSelectedSite(s.id)}><span className="site-dot" style={{background:s.enabled&&s.authorized?"#4ade80":"#64748b"}}/><span><b>{s.name}</b><small>{s.repository}</small><small>{s.live_url}</small></span><em>{s.enabled?"ENABLED":"DISABLED"}</em></button><div className="site-card-actions"><button onClick={()=>request("[Agent Runtime] Run "+s.name,{action:"claim",site:s.id})}>▶ Run Pipeline</button><button onClick={()=>request("[Site Manager] "+(s.enabled?"Disable ":"Enable ")+s.name,{action:s.enabled?"disable":"enable",id:s.id})}>{s.enabled?"Disable":"Enable"}</button><button onClick={()=>request("[Site Manager] Remove "+s.name,{action:"remove",id:s.id})}>Remove</button></div></div>)}</div><div className="site-actions"><button onClick={()=>setOpenAdd(v=>!v)}>＋ ADD SITE</button><a href="https://github.com/WebControlerAgent/WebControlerAgent.github.io/issues?q=is%3Aissue+label%3Asite-manager" target="_blank" rel="noreferrer">Open Site Manager</a></div>{openAdd&&<form className="site-form" onSubmit={submit}><b>ADD AUTHORIZED SITE</b><input placeholder="site-id e.g. my-site" value={form.id} onChange={e=>setForm({...form,id:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})}/><input placeholder="Site name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="GitHub repository owner/name" value={form.repository} onChange={e=>setForm({...form,repository:e.target.value})}/><input placeholder="Branch" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/><input placeholder="Live URL" value={form.live_url} onChange={e=>setForm({...form,live_url:e.target.value})}/><input placeholder="Media path (optional)" value={form.media_path} onChange={e=>setForm({...form,media_path:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><p>Adding a site creates a protected GitHub Site Manager request. It is not activated until the authorized registry is updated by Actions.</p><button type="submit">Create Site Request →</button></form>}</div></div>;
}

function App(){
 const [selected,setSelected]=useState<string|null>("manager"); const [sites,setSites]=useState<SiteRecord[]>([]); const [selectedSite,setSelectedSite]=useState("kingdom-raw"); const [sitesOpen,setSitesOpen]=useState(false); const [now,setNow]=useState(new Date()); const [status,setStatus]=useState<any>(null);
 const [chatOpen,setChatOpen]=useState(true);
 const runtimeAgents=useMemo(()=>{const raw=status?.agent_runtime?.agent_states??{};return agents.map(a=>({...a,runtimeState:raw[a.id]?.state??null,runtimeSite:raw[a.id]?.site??null,runtimeTask:raw[a.id]?.task??null,runtimeError:raw[a.id]?.error??null}));},[status]);
 const runtimeTone=(state:string|null,fallback:string)=>state==="FAILED"?"#fb7185":state==="REPAIRING"?"#fbbf24":state==="VERIFYING"?"#60a5fa":state==="COMPLETED"?"#34d399":state==="WORKING"?"#4ade80":fallback;
 const runtimeEvents=useMemo(()=>Array.isArray(status?.agent_runtime?.events)?status.agent_runtime.events.slice(-18).reverse():[],[status]);
 const liveEvents=runtimeEvents.filter((e:any)=>e.site===selectedSite || !e.site).slice(0,8);
 const refreshStatus=()=>fetch("./status.json?ts="+Date.now()).then(r=>r.ok?r.json():null).then(setStatus).catch(()=>{});
 const [chatInput,setChatInput]=useState("");
 const [messages,setMessages]=useState<{from:string;text:string;runtimeAction?:any;aiRequest?:string}[]>([{from:"Manager",text:"Studio online hai. Main actual Agent Runtime state read kar raha hoon. Status, queue, bug, ya kisi employee ka naam bolo."}]);
 const sendChat=()=>{const text=chatInput.trim();if(!text)return;const siteName=sites.find(s=>s.id===selectedSite)?.name??selectedSite;const enriched=text+`\\nActive site: ${siteName} (${selectedSite})`;const reply=managerReply(enriched,agents,status);if(reply.runtimeAction&&!reply.runtimeAction.site)reply.runtimeAction.site=selectedSite;setMessages(m=>[...m,{from:"You",text},{from:agents.find(a=>a.id===reply.agentId)?.name??"Manager",text:reply.text,runtimeAction:reply.runtimeAction,aiRequest:reply.aiRequest}]);setChatInput("");setSelected(reply.agentId);};
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{refreshStatus();fetch("./sites.json?ts="+Date.now()).then(r=>r.ok?r.json():null).then(d=>setSites(d?.sites??[])).catch(()=>{});const t=setInterval(refreshStatus,15000);return()=>clearInterval(t)},[]);
 const selectedAgent=agents.find(a=>a.id===selected)??agents[0];
 const runtimeSelected=runtimeAgents.find(a=>a.id===selectedAgent.id);
 const liveState=runtimeSelected?.runtimeState??null;
 const liveTask=runtimeSelected?.runtimeTask??selectedAgent.task;
 const liveError=runtimeSelected?.runtimeError??null;

 const counts=useMemo(()=>({working:runtimeAgents.filter(a=>a.runtimeState==="WORKING").length,active:runtimeAgents.filter(a=>a.runtimeState && a.runtimeState!=="IDLE").length}),[runtimeAgents]);
 return <div className="app">
  <header className="topbar3d"><div className="brand3d"><div className="brandmark">✦</div><div><b>AI AGENT WORKSPACE</b><span>Web Controller • Living Operations Office</span></div></div><div className="topstats"><span><i className="dot green"/> {counts.working} Working</span><span><i className="dot blue"/> {counts.active} Active</span><span className="system">● SYSTEM {status?.ok===false?"ATTENTION":"ONLINE"}</span><span className="clock">{now.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div></header>
  <div className="workspace">
   <aside className="sidebar"><div className="side-title">AGENTS <small>{agents.length}</small></div>{runtimeAgents.map(a=><button className={"agent-row "+(selected===a.id?"selected":"")} key={a.id} onClick={()=>setSelected(a.id)}><span className="mini-avatar" style={{background:a.color}}>{a.icon}</span><span><b>{a.name}</b><small>{a.runtimeState??a.status}</small></span><em style={{color:runtimeTone(a.runtimeState,a.accent)}}>●</em></button>)}<div className="legend"><b>LIVE OFFICE</b><p>Characters move through real destinations and show their current work state.</p><button onClick={()=>setSelected(null)}>View Whole Office</button></div></aside>
   <main className="scene"><div className="office-safe-mode"><div className="office-safe-head"><b>AGENT OPERATIONS FLOOR</b><span>LIVE GITHUB RUNTIME • 3D renderer isolated for stability</span></div><div className="office-agent-grid">{runtimeAgents.map(a=><button key={a.id} className={"office-agent office-state-"+String(a.runtimeState??a.status).toLowerCase()+" "+(selected===a.id?"selected":"")} onClick={()=>setSelected(a.id)}><span className="office-avatar" style={{background:a.color}}><i className="agent-glow" style={{background:a.accent}}></i><b>{a.icon}</b></span><span><b>{a.name}</b><small>{a.runtimeState??"IDLE"}</small><em style={{color:runtimeTone(a.runtimeState,a.accent)}}>●</em></span><i>{a.runtimeTask??a.task}</i></button>)}</div><div className="office-safe-note">The control system is live. Agent state, tasks, site selection, Manager chat, GitHub runtime and repair flow remain connected.</div></div>
    <div className="scene-title"><b>AI AGENT WORKSPACE</b><span>Isometric Operations Floor</span></div><div className="site-selector"><span>ACTIVE SITE</span><b>{sites.find(s=>s.id===selectedSite)?.name??"Loading sites..."}</b><button onClick={()=>setSitesOpen(true)}>⚙ Sites</button></div>
    <div className="scene-controls"><button onClick={()=>setSelected("manager")}>⌖ Focus Agent</button><button onClick={()=>setSelected(null)}>◎ Overview</button></div>
    <div className="activity"><b>LIVE ACTIVITY</b><span><i className="pulse"/> {selectedAgent.name} — {liveTask}</span><small>{liveState?`Runtime: ${liveState}`:"Waiting for runtime event"} • auto-refresh 15s</small></div><div className="site-dashboard"><div className="dashboard-head"><div><b>{sites.find(s=>s.id===selectedSite)?.name??selectedSite} / AGENT STATUS</b><small>{status?.agent_runtime?.active_site?("Active: "+status.agent_runtime.active_site.id):"No site currently claimed"} • auto-refresh 15s</small></div><button onClick={refreshStatus}>↻ Refresh</button></div><div className="dashboard-grid">{runtimeAgents.map(a=><button key={a.id} className="dash-agent" onClick={()=>setSelected(a.id)}><span className="dash-avatar" style={{background:a.color}}>{a.icon}</span><span><b>{a.name}</b><small>{a.runtimeState??"IDLE"}{a.runtimeTask?" • "+a.runtimeTask:""}</small>{a.runtimeError&&<em>{a.runtimeError}</em>}</span><i style={{color:runtimeTone(a.runtimeState,a.accent)}}>●</i></button>)}</div></div>
    {sitesOpen&&<SitePanel sites={sites} selectedSite={selectedSite} setSelectedSite={setSelectedSite} onClose={()=>setSitesOpen(false)}/>} {chatOpen&&<div className="chat-panel">
      <div className="chat-head"><div><b>MANAGER CHAT</b><small>Talk to the Agent Studio team • GitHub Runtime</small></div><button onClick={()=>setChatOpen(false)}>×</button></div>
      <div className="chat-messages">{messages.map((m,i)=><div key={i} className={"chat-msg "+(m.from==="You"?"you":"")}><span>{m.from}</span><p>{m.text}</p>{m.runtimeAction&&<a className="runtime-action" href={`https://github.com/WebControlerAgent/WebControlerAgent.github.io/issues/new?title=${encodeURIComponent("[Agent Runtime] "+m.runtimeAction.action)}&body=${encodeURIComponent("<!-- agent-runtime-command\n"+JSON.stringify(m.runtimeAction,null,2)+"\n-->")}`} target="_blank" rel="noreferrer">⚡ Send to GitHub Runtime</a>}{m.aiRequest&&<a className="runtime-action" href={`https://github.com/WebControlerAgent/WebControlerAgent.github.io/issues/new?title=${encodeURIComponent("[Manager AI] "+m.aiRequest.slice(0,60))}&body=${encodeURIComponent(m.aiRequest)}`} target="_blank" rel="noreferrer">🧠 Send to Manager AI</a>}</div>)}</div>
      <form className="chat-input" onSubmit={e=>{e.preventDefault();sendChat()}}>
        <input value={chatInput} onChange={e=>setChatInput(e.target.value)} placeholder="Ask Manager..." aria-label="Message Manager"/>
        <button type="submit" aria-label="Send message">➤</button>
      </form>
    </div>}
   </main>
   <aside className="inspector"><div className="inspector-head"><span>SELECTED AGENT</span><button onClick={()=>setSelected(null)}>×</button></div><div className="portrait" style={{background:selectedAgent.color}}><span>{selectedAgent.icon}</span><i style={{background:statusTone(selectedAgent.status)}}/></div><h2>{selectedAgent.name}</h2><p>{selectedAgent.role}</p><div className="status-card"><span>STATUS</span><b style={{color:liveState?runtimeTone(liveState,selectedAgent.accent):statusTone(selectedAgent.status)}}>● {liveState??selectedAgent.status}</b></div><div className="task-card"><span>CURRENT TASK</span><b>{liveTask}</b></div><div className="detail"><span>Destination</span><b>{selectedAgent.status==="WALKING"?"Moving through office":"Assigned workstation"}</b></div><div className="detail"><span>Workspace</span><b>Agent Studio</b></div><button className="talk" onClick={()=>setChatOpen(true)}>💬 Open employee channel</button><div className="timeline"><b>RECENT ACTIVITY</b>{liveEvents.length?liveEvents.slice(0,5).map((e:any,i)=><div className="timeline-event" key={i}><span>● {(e.type||"event").replaceAll("_"," ")}{e.task?": "+e.task:""}</span><small>{e.at?new Date(e.at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"live"}</small></div>):<><div>● Current state → {liveState??selectedAgent.status} <small>live</small></div><div>● Task → {liveTask} <small>live</small></div><div>● Next checkpoint <small>queued</small></div></>}{liveError&&<div className="runtime-error">⚠ {liveError}</div>}</div></aside>
  </div>
 </div>
}
createRoot(document.getElementById("root")!).render(<App/>);
window.dispatchEvent(new Event("agent-app-ready"));
